### ISSUE TITLE
[BUG] Not receiving stat data for some stashIds

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-backend-ts#18]
**Describe the bug**
For some stash ids, I’m not receiving the stats data, it says “data not available” which shouldn’t be the case. Stash id to test: `Ftx1pDVTVXbY5xWizEKngTfHkZXtUDUbwZBMQ33PAZh7zMs`

**Comment by sahilnanda1995** [comment]
resolved on call,
`Ftx1pDVTVXbY5xWizEKngTfHkZXtUDUbwZBMQ33PAZh7zMs` was not an actively staking stashId
