### ISSUE TITLE
Implement authentication via PolkadotJS wallet

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#26]
# TODO

### 🗒 &nbsp; Summary

The idea is to allow authenticated validators to update their off-chain info like team member info, bio, etc.

### ✅ &nbsp; Outcomes

The validator should be able to:

**Update team info:**
- [ ] Member name
- [ ] Member role
- [ ] Social link(s) [+P3 - good to have]

- [ ] Update bio
- [ ] Update logo

## ⏳ &nbsp; ETA

To be updated

**Comment by sahilnanda1995** [comment]
not a backend issue
