### ISSUE TITLE
[BUG] Check if nominators' value are stale if they un-bond / remove value from their account.

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-backend-ts#29]
**Describe the bug**
Check if nominators' value are stale if they un-bond / remove value from their account.
In the attached SS, there are no active nominations and API is returning old nominations.

P.S.: This might be due to the delay in updates.

![image](https://user-images.githubusercontent.com/22184427/86387250-8895b500-bcb0-11ea-83d4-31c66acf510e.png)

**Comment by sahilnanda1995** [comment]
@akshatbhargava123  can you provide the stashId's

**Comment by akshatbhargava123** [comment]
@sahilnanda1995, Stash id: `DasX1jVCRMe5e2DN8XJjGQrWFkBkNvtRDRf5dkb6iUUGFfz`
