### ISSUE TITLE
[BUG] Validator profile update API not working

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-backend-ts#31]
**Describe the bug**
- [x] Even though it shows "Info Updated" when I request for the same validator, I don't receive the updated members array.

![image](https://user-images.githubusercontent.com/22184427/86552065-86f41780-bf64-11ea-8e2d-124105d343a0.png)

- [x] There is no `field` to update the `description / tagline` of the validator.

- [x] Why are there fields for `stashId` and `connectedStashId` when we're already authenticating on frontend? Also, as it's an UPDATE request we're already posting the `stashId` field in the url params.

- [x] API should be `PUT` instead of `POST`, update operations should not be sent via POST. Read more here: https://restfulapi.net/rest-put-vs-post/
Even though ideal method to use in this case is `PUT`.

- [x] What is the `vision` field for?

**Comment by akshatbhargava123** [comment]
@sahilnanda1995, Is the fix deployed? Also, could you share the updated API request example please.

**Comment by sahilnanda1995** [comment]
> Is the fix deployed?
yep
> could you share the updated API request example please
body format:
```
{
    "vision": "vision",
    "members": [
        {
            "member": "member1",
            "role": "role1",
            "twitter": "twitter1"
        },
        {
            "member": "member2",
            "role": "role2",
            "twitter": "twitter2"
        }
    ]
}
```
PUT endpoint: /api/validator/:id/update
