### ISSUE TITLE
Display all selected nominations for selected stash account on user's overview tab

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#33]
# TODO

### 🗒 &nbsp; Summary
Display all selected nominations for selected stash account on user's overview tab (SS below)

![Screenshot 2020-07-06 at 5.54.51 PM.png](https://images.zenhubusercontent.com/5ea66c27c12ee929e35ae529/a4eb63e5-77c6-4746-a8ea-586468d7d26b)

### ✅ &nbsp; Outcomes
**Need to have**
- [ ] Add "isActive" param for all nominations + set to true for active and false for rest

**Good to have**
- [ ] All 3 labels for nominations - i.e. active, waiting and inactive

## ⏳ &nbsp; ETA
To be updated

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)

**Comment by sahilnanda1995** [comment]
added isElected, isWaiting and isNextElected keys for validators info
