### ISSUE TITLE
[BUG] Validator profile update API not working for some

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-backend-ts#34]
**Describe the bug**
Request URL: [https://yieldscan-api.onrender.com/api/validator/EDNEfKXHd645DPpBhLZjaEwp4sPhj4STjjS4QrMbFU1FqbZ/update
](https://yieldscan-api.onrender.com/api/validator/EDNEfKXHd645DPpBhLZjaEwp4sPhj4STjjS4QrMbFU1FqbZ/update
)

Payload:
![image](https://user-images.githubusercontent.com/22184427/86907929-61693880-c133-11ea-8c98-7060cb61efe9.png)

**Comment by sahilnanda1995** [comment]
worked for me
payload:
```
{
    "vision": "vision",
    "members": [
        {
            "member": "member1",
            "role": "role1",
            "twitter": "twitter1"
        },
        {
            "member": "member2",
            "twitter": "twitter2"
        }
    ]
}
```
after updating, response:
![image](https://user-images.githubusercontent.com/41546731/86910758-cf176380-c137-11ea-9483-d026bfab7cc5.png)

change "name" to "member"
