### ISSUE TITLE
Should follow some API specs

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-backend-ts#4]
- [x] APIs should return objects with required keys
- [x] Follow REST guidelines, `max reward` and `risk-based reward` calculation should come under `/reward-calculation` API namespace and then we can have `max` and `risk-based`

**Comment by saumyakaran** [comment]
@akshatbhargava123 Possible to assign priority label to this issue + any other labels that might be relevant?
