### ISSUE TITLE
[TODO] M2 Resubmission fixes - backend

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#41]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

Try to be as specific as possible. Think about falsifiable outcomes.

**Refer:** [SMART Goal Examples](https://www.thebalancesmb.com/smart-goal-examples-2951827)

### 🗒 &nbsp; Summary
A brief overview of the problem to be solved. Include all relevant data points.

### ✅ &nbsp; Outcomes
- [x]  The backend currently doesn’t compile locally, [see attached error (error-env-file)](https://buidllabs.slack.com/archives/C0113AU1XUG/p1595345507007400).
    - [x]  Update README with a guide on how to run backend locally so that it compiles + functions for someone who has no experience with our codebase

## ⏳ &nbsp; ETA
TBD

If you don't specify a timezone, by default IST shall be assumed.

Refer: [ETA culture document](https://docs.google.com/document/d/1ZGa6diesOmx-jSBjm0uj8j4oN75gYqux85qA7DJOm68/edit)

---

Relevant files are attached [here](https://buidllabs.slack.com/archives/C0113AU1XUG/p1595345507007400)

**Comment by sahilnanda1995** [comment]
done
https://github.com/buidl-labs/yieldscan-backend-ts/pull/42
