### ISSUE TITLE
[FEATURE_REQUEST] Endpoint for fetching validators' data

### ISSUE THREAD

**Issue by akshatbhargava123** [buidl-labs/yieldscan-backend-ts#45]
**Describe the solution you'd like**
Endpoint for fetching validators' data. API will take as input the set of validator's kusama stash-ids and return the full data for the validators.

**Comment by sahilnanda1995** [comment]
done,
https://buidllabs.slack.com/archives/C013YJWJY04/p1596197028000600?thread_ts=1596196412.000500&cid=C013YJWJY04
