### ISSUE TITLE
[BUG] Investigate data discrepancy issue with ownStake and totalStake

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#46]
**Describe the bug**

- Seems like there's some issue with the own/other stake data (probably a backend issue - cc @sahilnanda1995):

    - [UPDATE on the data issue] The data seems to be fine now - I'm not sure what was the reason behind the discrepancy but seems to be working fine for now - nevertheless, we should probably investigate this

<img width="1440" alt="Screenshot 2020-07-31 at 10 58 21 AM" src="https://user-images.githubusercontent.com/40575379/89003231-de479680-d31c-11ea-87a6-102f1ca61433.png">

Originally mentioned [here](https://github.com/buidl-labs/yieldscan-frontend/pull/52#issuecomment-666938514).

**To Reproduce**

Unsure - this issue is to investigate the same

**Comment by sahilnanda1995** [comment]
fixed
