### ISSUE TITLE
[BUG] The number of nominations for certain nominators exceeds 16, which isn't possible

### ISSUE THREAD

**Issue by saumyakaran** [buidl-labs/yieldscan-backend-ts#51]
**Describe the bug**
The number of nominations for certain nominators exceeds 16, which isn't possible + this doesn't match the data on Polkastats.

**To Reproduce**
Visit the nominators page on yieldscan.onrender.com/nominators

**Screenshots**
<img width="1440" alt="Screenshot 2020-08-15 at 10 18 16 AM" src="https://user-images.githubusercontent.com/40575379/90305469-db35d400-dee0-11ea-9ae8-7be9e32b7398.png">

**Comment by sahilnanda1995** [comment]
fixed
