### ISSUE TITLE
[BUG] Nominators data discrepancy

### ISSUE THREAD

**Issue by joyboyisfree** [buidl-labs/yieldscan-backend-ts#69]
**Describe the bug**
Daily earnings for nominators shows as 0 for all. Also, the sorting of the nominators table seems to be random - top 3 validators don't seem to have the most amount staked.

This is happening for both networks.

**Screenshots**
<img width="1914" alt="Screenshot 2020-10-21 at 10 19 29 AM" src="https://user-images.githubusercontent.com/40575379/96674937-720e8900-1387-11eb-83b4-476ac2c02210.png">

**Comment by sahilnanda1995** [comment]
fixed
